# Welcome to Plus!
#
# This config file affects your whole blog.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title:              Hi! I'm Fab
description:        This is my personal website. A place for though sharing and ideas spreading. Everything here is on my own and it doesn't reflect my employer's opinion.
url:                https://fabriciosanchez.com
baseurl:            "" # Site subpath, e.g. /blog
logo_image:
  dark:             # Dark logo e.g logo-dark.svg upload to /uploads/ folder, used in header, mobile navigation and page sidebar About widget
  light:            # Light logo e.g. logo-light.svg upload to /uploads/ folder, used in footer About widget
permalink:          /:title/ # Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
date_format:        "%B %-d, %Y" # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
uploads:            /uploads/ # Path to post content assets directory i.e post images, pdfs etc
paginate:           7 # Number of posts displayed on blog page
paginate_path:      "/blog/:num/" # Blog path
google_analytics:   G-03HEL6293N
disqus:
  shortname:        # Disqus comments shortname, requires Disqus account https://disqus.com/

instagram_accesstoken: 

footer:             # Default footer image settings
  copyright:        Fabricio Sanchez - All rights reserved. Gentle hosted by <a href='https://github.com' target='_blank' >Github Pages</a>.

# navbar settings
navbar_primary:
  sticky:           true
  social:           true
  search:           true

# Social share buttons
social_share:
  twitter:          true
  facebook:         true
  linkedin:         true
  pinterest:        true
  reddit:           true

# Social networks
social_networks:
  email:          
  website:        
  facebook:         
  flickr:         
  dribbble:       
  github:           https://github.com/fabriciosanchez/
  reddit:         
  instagram:        https://www.instagram.com/sanchezfabricio/
  linkedin:         https://www.linkedin.com/in/fabriciosanchez/
  pinterest:      
  twitter:          https://twitter.com/sanchezfabricio
  vimeo:          
  youtube:          https://www.youtube.com/channel/UC6il5eEbwInXJ8X3Ip7QMQw    

# Strings
strings:
  author_by:        By

# Build settings
markdown:           kramdown
highlighter:        rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - CHANGELOG
  - LICENSE
  - README
  - /docs

sass:
  style:            compressed

# collections:
collections:
  authors:
    output: true
  category:
    output: true

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      sidebar: left
  # _authors
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  # _category
  - scope:
      path: ""
      type: category
    values:
      layout: category